// src/svelte/containers/page.svelte
<script>
  import Aside from '../components/aside.svelte';
  import Heading from '../components/heading.svelte';
  import Nav from '../components/nav.svelte';
  import Main from '../components/main.svelte';
  import Masthead from '../components/masthead.svelte';
  import Prose from '../components/prose.svelte';
  import Wrapper from '../components/wrapper.svelte';

  export let body;
  export let latest;
  export let title;
</script>

<Wrapper>
  <Masthead />
  <Main>
    <Nav />
    <Heading {title} />
    <Prose innerHTML={body} />
  </Main>
  <Aside articles={latest} />
</Wrapper>

// src/containers/page.jsx
import React from 'react';
import Aside from '../components/aside';
import Nav from '../components/nav';
import Main from '../components/main';
import Masthead from '../components/masthead';
import Prose from '../components/prose';
import Wrapper from '../components/wrapper';
import Heading from '../components/heading';

const Container = (props) => {
  return (
    <Wrapper>
      <Masthead />
      <Main>
        <Nav />
        <Heading title={props.title} />
        <Prose innerHTML={props.body} />
      </Main>
      <Aside articles={props.latest} />
    </Wrapper>
  );
};

export default Container;
