// src/react/components/article.jsx
import React from 'react';
import Time from './time';

const Article = (props) => {
  return (
    <article className='Article'>
      <h2 className='Star'>
        <a href={props.href} dangerouslySetInnerHTML={{__html: props.title}} />
      </h2>
      {props.date && <Time {...props.date} />}
      {props.excerpt && <p>{props.excerpt}</p>}
    </article>
  );
};

export default Article;

// src/svelte/components/article.svelte
<script>
  import Time from './time.svelte';

  export let date;
  export let excerpt;
  export let href;
  export let title;
</script>

<article class="Article">
  <h2 class="Star">
    <a {href}>{@html title}</a>
  </h2>
  {#if date}
    <Time {...date} />
  {/if}
  {#if excerpt}
    <p>{excerpt}</p>
  {/if}
</article>
