// src/components/masthead.jsx
import React from 'react';
import Logo from './logo';

const Masthead = () => {
  return (
    <div className='Masthead'>
      <div id='logo'>
        <Logo />
      </div>
      <a className='Sign' href='/contact/'>
        <img
          alt='Get in Touch I’m Available for Hire'
          width='540'
          height='325'
          loading='lazy'
          src='/assets/img/dbushell-for-hire.svg'
        />
      </a>
    </div>
  );
};

export default Masthead;

// src/svelte/components/masthead.svelte
<script>
  import Logo from './logo.svelte';
</script>

<div class="Masthead">
  <div id="logo">
    <Logo />
  </div>
  <a class="Sign" href="/contact/">
    <span class="Hidden">Contact</span>
    <img
      alt="Get in Touch I’m Available for Hire"
      width="540"
      height="325"
      loading="lazy"
      src="/assets/img/dbushell-for-hire.svg" />
  </a>
</div>
