// src/svelte/containers/archive.svelte
<script>
  import Article from '../components/article.svelte';
  import Aside from '../components/aside.svelte';
  import Button from '../components/button.svelte';
  import Heading from '../components/heading.svelte';
  import Nav from '../components/nav.svelte';
  import Main from '../components/main.svelte';
  import Masthead from '../components/masthead.svelte';
  import Wrapper from '../components/wrapper.svelte';

  export let articles;
  export let latest;
  export let next;
  export let prev;
  export let title;
</script>

<Wrapper>
  <Masthead />
  <Main>
    <Nav />
    <Heading {title} />
    {#each articles as item (item.unix)}
      <Article key={item.unix} {...item} />
    {/each}
    {#if next || prev}
      <div class="Pagination">
        {#if prev}
          <Button href={prev}>Previous</Button>
        {/if}
        {#if next}
          <Button href={next}>Next</Button>
        {/if}
      </div>
    {/if}
  </Main>
  <Aside articles={latest} />
</Wrapper>

// src/react/containers/archive.jsx
import React from 'react';
import Aside from '../components/aside';
import Nav from '../components/nav';
import Main from '../components/main';
import Masthead from '../components/masthead';
import Article from '../components/article';
import Button from '../components/button';
import Wrapper from '../components/wrapper';
import Heading from '../components/heading';

const Pagination = (props) => {
  if (!props.next && !props.prev) {
    return null;
  }
  return (
    <div className="Pagination">
      {props.prev && <Button href={props.prev}>Previous</Button>}
      {props.next && <Button href={props.next}>Next</Button>}
    </div>
  );
};

const Container = (props) => {
  return (
    <Wrapper>
      <Masthead />
      <Main>
        <Nav />
        <Heading title={props.title} />
        {props.articles.map(function (item) {
          return <Article key={item.unix} {...item} />;
        })}
        <Pagination {...props} />
      </Main>
      <Aside articles={props.latest} />
    </Wrapper>
  );
};

export default Container;
