// src/svelte/components/nav.svelte
<nav class="Nav">
  <h2 class="Hidden">Menu</h2>
  <ul>
    <li>
      <a href="/">
        <span class="Hidden">Home</span>
        <svg
          width="19.34"
          height="18.75"
          viewBox="0 0 19.34 18.75"
          role="presentation">
          <path
            d="M9.67 0a1.08 1.08 0 00-.54.15L.51 5.37a1.06 1.06 0 00-.36 1.45 1.07 1.07 0 00.9.5 1.08 1.08 0 00.55-.15l8.07-4.89c2.7 1.63 5.37 3.22 8.09 4.82a1 1 0 00.53.14 1.01 1.01 0 00.53-1.95l-4.31-2.53-4.28-2.6A1.1 1.1 0 009.67 0z" />
          <path d="M2.22 18V9.16l7.45-4.49q3.72 2.24 7.45 4.43h0v8.92z" />
        </svg>
      </a>
    </li>
    <li>
      <a href="/contact/">
        <span class="Hidden">Contact</span>
        <svg
          width="21.01"
          height="18"
          viewBox="0 0 21.01 18"
          role="presentation">
          <path
            d="M10.19 13.83h7.83a3 3 0 003-3V3.02a3.14 3.14 0 00-3.06-3h-15a3 3 0 00-3 3v7.91a3 3 0 002.95 3 .26.26 0 01.25.26v2a1.94 1.94 0 001.19 1.77 1.73 1.73 0 00.75.14 1.89 1.89 0 001.36-.58l3.51-3.51a.25.25 0 01.22-.18zm-1.17-1.37l-3.66 3.62a.27.27 0 01-.18.08h-.1a.25.25 0 01-.16-.24v-2.89a.86.86 0 00-.86-.86h-1a1.27 1.27 0 01-1.26-1.26V3.02a1.27 1.27 0 011.26-1.26h15a1.27 1.27 0 011.26 1.26v7.91a.22.22 0 01-.09.19 1.28 1.28 0 01-1.24 1.07H9.65a.84.84 0 00-.63.27z" />
          <circle cx="5.61" cy="6.96" r="1.29" />
          <circle cx="10.47" cy="6.96" r="1.29" />
          <circle cx="15.29" cy="6.96" r="1.29" />
        </svg>
      </a>
    </li>
    <li><a href="/about/"><span>About</span></a></li>
    <li><a href="/services/"><span>Services</span></a></li>
    <li><a href="/showcase/"><span>Work</span></a></li>
    <li><a href="/blog/"><span>Blog</span></a></li>
  </ul>
</nav>

// src/react/components/nav.jsx
import React from 'react';

const Nav = () => {
  return (
    <nav className='Nav'>
      <h2 className='Hidden'>Menu</h2>
      <ul>
        <li>
          <a href='/'>
            <span className='Hidden'>Home</span>
            <svg
              width='19.34'
              height='18.75'
              viewBox='0 0 19.34 18.75'
              role='presentation'
            >
              <path d='M9.67 0a1.08 1.08 0 00-.54.15L.51 5.37a1.06 1.06 0 00-.36 1.45 1.07 1.07 0 00.9.5 1.08 1.08 0 00.55-.15l8.07-4.89c2.7 1.63 5.37 3.22 8.09 4.82a1 1 0 00.53.14 1.01 1.01 0 00.53-1.95l-4.31-2.53-4.28-2.6A1.1 1.1 0 009.67 0z' />
              <path d='M2.22 18V9.16l7.45-4.49q3.72 2.24 7.45 4.43h0v8.92z' />
            </svg>
          </a>
        </li>
        <li>
          <a href='/contact/'>
            <span className='Hidden'>Contact</span>
            <svg
              width='21.01'
              height='18'
              viewBox='0 0 21.01 18'
              role='presentation'
            >
              <path d='M10.19 13.83h7.83a3 3 0 003-3V3.02a3.14 3.14 0 00-3.06-3h-15a3 3 0 00-3 3v7.91a3 3 0 002.95 3 .26.26 0 01.25.26v2a1.94 1.94 0 001.19 1.77 1.73 1.73 0 00.75.14 1.89 1.89 0 001.36-.58l3.51-3.51a.25.25 0 01.22-.18zm-1.17-1.37l-3.66 3.62a.27.27 0 01-.18.08h-.1a.25.25 0 01-.16-.24v-2.89a.86.86 0 00-.86-.86h-1a1.27 1.27 0 01-1.26-1.26V3.02a1.27 1.27 0 011.26-1.26h15a1.27 1.27 0 011.26 1.26v7.91a.22.22 0 01-.09.19 1.28 1.28 0 01-1.24 1.07H9.65a.84.84 0 00-.63.27z' />
              <circle cx='5.61' cy='6.96' r='1.29' />
              <circle cx='10.47' cy='6.96' r='1.29' />
              <circle cx='15.29' cy='6.96' r='1.29' />
            </svg>
          </a>
        </li>
        <li>
          <a href='/about/'>
            <span>About</span>
          </a>
        </li>
        <li>
          <a href='/services/'>
            <span>Services</span>
          </a>
        </li>
        <li>
          <a href='/showcase/'>
            <span>Work</span>
          </a>
        </li>
        <li>
          <a href='/blog/'>
            <span>Blog</span>
          </a>
        </li>
      </ul>
    </nav>
  );
};

export default Nav;
